### ISSUE TITLE
[Task] [Document] Project part B: Analysis description

### ISSUE THREAD

**Issue by huangyz0918** [UCLA-CS130-23Fall/EasySplit#18]
## Analysis Description
- Analyze the functional requirements of your application and capture it with UML
Diagrams. **Please accompany each diagram with a brief textual caption that describes its purpose. Include the following UML diagrams in your report**.
    - Describe the use cases of your application and the actors and external systems involved in them with a **Use Case Diagram**. Please include one use case diagram for the entire application.
    - Describe the actions of each actor and system and the control flow between them for your most important use cases with **Activity Diagrams**. Please include one or two activity diagrams showing your most important components in your application.
    - Describe the classes and data structures of your application and their attributes, relations and operations with a **Class Diagram**. Please include one class diagram for the entire application.
    - Describe some scenarios of the identified use cases involving the actors and classes of your application with **Sequence Diagrams**. Please include one or two sequence diagrams showing your most important components in your application.
    - Describe the behavior of your most complex classes (of the system as a whole) and how it responds to events with **State Machine Diagrams**. Please include one or two state machine diagrams showing your most important components in your application.
- Explain how your diagrams correspond to the functional requirements in your application.

## Tasks

- [x] Use Case Diagram
- [x] Activity Diagrams
- [x] Class Diagram
- [x] Sequence Diagrams
- [x] State Machine Diagrams

### Document Link

https://docs.google.com/document/d/16b7Zf7Xr2PhzUmUNTw1aufKztwdk8E14w6X99ZI6VBg/edit?usp=sharing

**Comment by yijinhua** [comment]
Lucas will work on use case and state machine diagrams
Yijin will work on class, activity, and sequence diagrams

**Comment by yijinhua** [comment]
completed
